-- Generated by Oracle SQL Developer Data Modeler 21.4.2.059.0838
--   at:        2022-06-08 02:46:45 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE t_sm_caso (
    id_caso               NUMBER(10) NOT NULL,
    t_sm_sexo_id_sexo     NUMBER(1) NOT NULL,
    dt_nasc               DATE NOT NULL,
    t_sm_ensino_id_ensino NUMBER(2) NOT NULL,
    dt_caso               DATE NOT NULL,
    t_sm_cidade_id_cidade NUMBER(4) NOT NULL,
    t_sm_doenca_id_doenca NUMBER(3) NOT NULL,
    nr_renda              NUMBER(7, 2)
);

ALTER TABLE t_sm_caso ADD CONSTRAINT t_sm_caso_pk PRIMARY KEY ( id_caso );

CREATE TABLE t_sm_caso_vacina (
    id_relacao            NUMBER(3) NOT NULL,
    t_sm_vacina_id_vacina NUMBER(3) NOT NULL,
    t_sm_caso_id_caso     NUMBER(10) NOT NULL,
    t_sm_obito_id_obito   NUMBER(10) NOT NULL,
    id_obito1             NUMBER NOT NULL
);

ALTER TABLE t_sm_caso_vacina ADD CONSTRAINT t_sm_caso_vacina_pk PRIMARY KEY ( id_relacao );

CREATE TABLE t_sm_cidade (
    id_cidade             NUMBER(4) NOT NULL,
    t_sm_estado_id_estado NUMBER(2) NOT NULL,
    nm_cidade             VARCHAR2(50) NOT NULL,
    nr_agente             NUMBER(3)
);

ALTER TABLE t_sm_cidade ADD CONSTRAINT t_sm_cidade_pk PRIMARY KEY ( id_cidade );

CREATE TABLE t_sm_doenca (
    id_doenca NUMBER(3) NOT NULL,
    nm_doenca VARCHAR2(100) NOT NULL,
    bl_vacina CHAR(1)
);

ALTER TABLE t_sm_doenca ADD CONSTRAINT t_sm_doenca_pk PRIMARY KEY ( id_doenca );

CREATE TABLE t_sm_ensino (
    id_ensino NUMBER(2) NOT NULL,
    ds_ensino VARCHAR2(40) NOT NULL
);

ALTER TABLE t_sm_ensino ADD CONSTRAINT t_sm_ensino_pk PRIMARY KEY ( id_ensino );

CREATE TABLE t_sm_estado (
    id_estado             NUMBER(2) NOT NULL,
    t_sm_regiao_id_regiao NUMBER(1) NOT NULL,
    nm_estado             VARCHAR2(40) NOT NULL,
    ds_abreviacao         CHAR(2) NOT NULL
);

ALTER TABLE t_sm_estado ADD CONSTRAINT t_sm_estado_pk PRIMARY KEY ( id_estado );

CREATE TABLE t_sm_obito (
    id_obito              NUMBER(10) NOT NULL,
    t_sm_doenca_id_doenca NUMBER(3) NOT NULL,
    t_sm_cidade_id_cidade NUMBER(4) NOT NULL,
    dt_obito              DATE NOT NULL,
    t_sm_sexo_id_sexo     NUMBER(1) NOT NULL,
    dt_nasc               DATE NOT NULL,
    t_sm_ensino_id_ensino NUMBER(2) NOT NULL,
    nr_renda              NUMBER(7, 2)
);

ALTER TABLE t_sm_obito ADD CONSTRAINT t_sm_obito_pk PRIMARY KEY ( id_obito );

CREATE TABLE t_sm_pais (
    id_pais       NUMBER(3) NOT NULL,
    nm_pais       VARCHAR2(40) NOT NULL,
    ds_abreviacao CHAR(2),
    ds_iso_alpha3 CHAR(3),
    nr_ddi        NUMBER(3)
);

ALTER TABLE t_sm_pais ADD CONSTRAINT t_sm_pais_pk PRIMARY KEY ( id_pais );

CREATE TABLE t_sm_regiao (
    id_regiao         NUMBER(1) NOT NULL,
    t_sm_pais_id_pais NUMBER(3) NOT NULL,
    nm_regiao         VARCHAR2(50) NOT NULL
);

ALTER TABLE t_sm_regiao ADD CONSTRAINT t_sm_regiao_pk PRIMARY KEY ( id_regiao );

CREATE TABLE t_sm_sexo (
    id_sexo NUMBER(1) NOT NULL,
    ds_sexo VARCHAR2(10) NOT NULL
);

ALTER TABLE t_sm_sexo ADD CONSTRAINT t_sm_sexo_pk PRIMARY KEY ( id_sexo );

CREATE TABLE t_sm_vacina (
    id_vacina             NUMBER(3) NOT NULL,
    t_sm_doenca_id_doenca NUMBER(3) NOT NULL,
    nm_vacina             VARCHAR2(40) NOT NULL,
    nm_laboratorio        VARCHAR2(40) NOT NULL
);

ALTER TABLE t_sm_vacina ADD CONSTRAINT t_sm_vacina_pk PRIMARY KEY ( id_vacina );

ALTER TABLE t_sm_caso
    ADD CONSTRAINT t_sm_caso_t_sm_cidade_fk FOREIGN KEY ( t_sm_cidade_id_cidade )
        REFERENCES t_sm_cidade ( id_cidade );

ALTER TABLE t_sm_caso
    ADD CONSTRAINT t_sm_caso_t_sm_doenca_fk FOREIGN KEY ( t_sm_doenca_id_doenca )
        REFERENCES t_sm_doenca ( id_doenca );

ALTER TABLE t_sm_caso
    ADD CONSTRAINT t_sm_caso_t_sm_ensino_fk FOREIGN KEY ( t_sm_ensino_id_ensino )
        REFERENCES t_sm_ensino ( id_ensino );

ALTER TABLE t_sm_caso
    ADD CONSTRAINT t_sm_caso_t_sm_sexo_fk FOREIGN KEY ( t_sm_sexo_id_sexo )
        REFERENCES t_sm_sexo ( id_sexo );

ALTER TABLE t_sm_caso_vacina
    ADD CONSTRAINT t_sm_caso_vac_t_sm_caso_fk FOREIGN KEY ( t_sm_caso_id_caso )
        REFERENCES t_sm_caso ( id_caso );

ALTER TABLE t_sm_caso_vacina
    ADD CONSTRAINT t_sm_caso_vac_t_sm_obito_fk FOREIGN KEY ( t_sm_obito_id_obito )
        REFERENCES t_sm_obito ( id_obito );

ALTER TABLE t_sm_caso_vacina
    ADD CONSTRAINT t_sm_caso_vac_t_sm_vacina_fk FOREIGN KEY ( t_sm_vacina_id_vacina )
        REFERENCES t_sm_vacina ( id_vacina )
            ON DELETE CASCADE;

ALTER TABLE t_sm_cidade
    ADD CONSTRAINT t_sm_cidade_t_sm_estado_fk FOREIGN KEY ( t_sm_estado_id_estado )
        REFERENCES t_sm_estado ( id_estado )
            ON DELETE CASCADE;

ALTER TABLE t_sm_estado
    ADD CONSTRAINT t_sm_estado_t_sm_regiao_fk FOREIGN KEY ( t_sm_regiao_id_regiao )
        REFERENCES t_sm_regiao ( id_regiao )
            ON DELETE CASCADE;

ALTER TABLE t_sm_obito
    ADD CONSTRAINT t_sm_obito_t_sm_cidade_fk FOREIGN KEY ( t_sm_cidade_id_cidade )
        REFERENCES t_sm_cidade ( id_cidade );

ALTER TABLE t_sm_obito
    ADD CONSTRAINT t_sm_obito_t_sm_doenca_fk FOREIGN KEY ( t_sm_doenca_id_doenca )
        REFERENCES t_sm_doenca ( id_doenca );

ALTER TABLE t_sm_obito
    ADD CONSTRAINT t_sm_obito_t_sm_ensino_fk FOREIGN KEY ( t_sm_ensino_id_ensino )
        REFERENCES t_sm_ensino ( id_ensino );

ALTER TABLE t_sm_obito
    ADD CONSTRAINT t_sm_obito_t_sm_sexo_fk FOREIGN KEY ( t_sm_sexo_id_sexo )
        REFERENCES t_sm_sexo ( id_sexo );

ALTER TABLE t_sm_regiao
    ADD CONSTRAINT t_sm_regiao_t_sm_pais_fk FOREIGN KEY ( t_sm_pais_id_pais )
        REFERENCES t_sm_pais ( id_pais )
            ON DELETE CASCADE;

ALTER TABLE t_sm_vacina
    ADD CONSTRAINT t_sm_vacina_t_sm_doenca_fk FOREIGN KEY ( t_sm_doenca_id_doenca )
        REFERENCES t_sm_doenca ( id_doenca )
            ON DELETE CASCADE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             26
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
