-- INSERINDO DADOS NA TABELA T_SM_DOENCA
INSERT INTO T_SM_DOENCA VALUES (SQ_SM_DOENCA.nextval, 'Dengue', 1);
INSERT INTO T_SM_DOENCA VALUES (SQ_SM_DOENCA.nextval, 'Malaria', 1); 
INSERT INTO T_SM_DOENCA VALUES (SQ_SM_DOENCA.nextval, 'Zika', 0);